### ISSUE TITLE
Feature: User can delete their decks

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/majax#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality
Users should be able to see a trash can icon on desktop that will let them delete their decks,
mobile users should be able to long press on a deck to delete it. Both actions should show the modal in the wire frame.
> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal that displays a confirmation message with two buttons
- [x] Make sure modal matches wireframe
- [ ] Add event listeners to the buttons that deletes the active deck, or not.
- [ ] Make sure to delete the deck and its image in local storage as well.
- [ ] Hide the modal after user chooses an action
- [ ] Add the modal to the switchview function
- [ ] Add a trash can icon to all deck boxes that are hidden and shown when that deck is active on desktop
- [ ] Make sure that the deck boxes still match the wire frame
- [ ] Use bubbling on desktop deck list to see if data-control is equal to delete, if so call switchview to show modal
- [ ] Do the same but for the mobile list, and instead of on click, find out a way to make it a long press.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
