### ISSUE TITLE
Bug:  Performance Issue

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/majax#26]
#### Desired Behavior

> ##### The app should ...
Be faster on mobile and desktop

#### Actual Behavior
> ##### The app does this instead ...
The app performs poorly on low end desktops and  phones.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...
have a bad device

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Limit the amount of cards that can display on mobile.
- [x] Use large images only when needed
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
