### ISSUE TITLE
Feature: User can import and export their decks to and from from QR codes.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/majax#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop Modal](https://user-images.githubusercontent.com/16251746/128426661-b5815aa7-99b9-407a-8e08-e608b8b7d7a9.png)
![Mobile QR Modal](https://user-images.githubusercontent.com/16251746/128426692-eee64a03-be89-474a-baa7-f4d9cf97dc96.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Copy paste the info modal and turn it into a qr modal
- [ ] Add the qr modal to the switchView function
- [ ] Add an event handler to the qr icon that shows the qr modal.
- [ ] When the user taps anywhere on the qr modal, close the qr modal.
- [ ] concatenate 'https://humbertovnavarro.github.io/ajax-project?  with deck.serialize.
- [ ] Take the value from above and add that to the end of the QRCode API url. Set the qr modal to the resulting url in its switchView conditional, before switching.
- [ ] Take the value of window.location.search, and convert that into a new deck on load, if it exists.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
